### ISSUE TITLE
Unable to download resnet50 pretrained model

### ISSUE THREAD

**Issue by nshreyasvi** [bknyaz/videos#1]
Hello,
I was trying to download the pretrained model from the amazon link but it doesn't work. Could you provide an alternate link from where I can download it ?

**Comment by bknyaz** [comment]
Hi, I could not find another link. I'm using PyTorch now and it downloads this model automatically, you can probably convert it from PyTorch to Lasagne.

**Comment by nshreyasvi** [comment]
Is it possible to upload it to google drive ? In the other case, I was trying to convert it from caffe to pickle.
Could you also share the link to the pytorch pretrained model ?

**Comment by bknyaz** [comment]
The links for PyTorch models are here: https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
Converting from Caffe is a also a good idea. 

I could not find my pickle file, it's an old project and I didn't save the models.

**Comment by nshreyasvi** [comment]
ok, do you know any github implementation of the same system in pytorch or keras ?
I am using the following method right now to convert to pickle format:
https://github.com/Lasagne/Recipes/blob/master/examples/resnet50/ImageNet%20Pretrained%20Network%20(ResNet-50).ipynb

**Comment by nshreyasvi** [comment]
Ok, so I think I can just paste the link here: https://drive.google.com/file/d/1BOdAkUbD7sqihaDJekB4XJMqB2fE6aNc/view?usp=sharing
This is the resnet50.pkl pre-trained model
Thanks for quick replies, I will close this issue then

**Comment by bknyaz** [comment]
Ok, no problem.
